### ISSUE TITLE
npm start doesn't work

### ISSUE THREAD

**Issue by adnjoo** [andrewnjoo/inferno#1]
```bash
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/andrewnjoo/Desktop/my-app/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/Users/andrewnjoo/Desktop/my-app/node_modules/webpack/lib/NormalModule.js:386:16)
    at handleParseError (/Users/andrewnjoo/Desktop/my-app/node_modules/webpack/lib/NormalModule.js:434:10)
    at /Users/andrewnjoo/Desktop/my-app/node_modules/webpack/lib/NormalModule.js:466:5
    at /Users/andrewnjoo/Desktop/my-app/node_modules/webpack/lib/NormalModule.js:327:12
    at /Users/andrewnjoo/Desktop/my-app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/andrewnjoo/Desktop/my-app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/andrewnjoo/Desktop/my-app/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/Users/andrewnjoo/Desktop/my-app/node_modules/inferno-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/andrewnjoo/Desktop/my-app/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/Users/andrewnjoo/Desktop/my-app/node_modules/webpack/lib/NormalModule.js:386:16)
    at /Users/andrewnjoo/Desktop/my-app/node_modules/webpack/lib/NormalModule.js:418:10
    at /Users/andrewnjoo/Desktop/my-app/node_modules/webpack/lib/NormalModule.js:293:13
    at /Users/andrewnjoo/Desktop/my-app/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/andrewnjoo/Desktop/my-app/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/andrewnjoo/Desktop/my-app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/andrewnjoo/Desktop/my-app/node_modules/inferno-scripts/node_modules/babel-loader/lib/index.js:51:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.16.0
```

**Comment by adnjoo** [comment]
[1 - SO](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported)
[2 - FCC](https://www.freecodecamp.org/news/error-error-0308010c-digital-envelope-routines-unsupported-node-error-solved/)

**Comment by adnjoo** [comment]
pass ` --openssl-legacy-provider` to `start` script

The option "--openssl-legacy-provider" refers to a flag used with the OpenSSL command-line tool. OpenSSL is a widely used open-source library for secure communications and cryptographic functions.

In versions prior to OpenSSL 3.0, there were multiple providers available for different cryptographic algorithms. The "--openssl-legacy-provider" flag is used to specify the use of the legacy provider in OpenSSL 3.0 and later versions. The legacy provider maintains backward compatibility with older OpenSSL versions and ensures compatibility with applications that rely on specific behavior or features of the legacy implementation.

By using the "--openssl-legacy-provider" flag, you indicate that you want to utilize the legacy provider instead of the default provider in OpenSSL 3.0 and onwards. This can be helpful when you need to ensure compatibility with older systems or applications that may not support the updated provider in OpenSSL 3.0.
